version: "3.1"
services:
    reverse-proxy:
        build: reverse-proxy/.
        image: reverse-proxy:latest
        ports:
            - "5000:80"
            - "5001:5001"
        depends_on:
            - frontend

    db:
        build: DB/
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: vehicledb

    backend:
        build: VehicleApplicationBackend/
        image: vehicle-application-backend
        depends_on:
            - db

    frontend:
        build: VehicleApplicationFrontend/
        image: vehicle-application-frontend
        depends_on:
            - backend

    simulator:
        build: VehicleSimulator/VehicleSimulator/
        image: vehicle-application-simulator
        depends_on:
            - backend
        

