version: "3.1"
services:
    db:
        build: DB/
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: vehicledb

    backend:
        build: VehicleApplicationBackend/
        depends_on:
            - db
        ports:
            - "8080:80"
        

